module.exports = {
    request_logs: 'server3',
    user_accounts: 'server1',
    sentiment_patterns: 'server0',
    sentiment_vocabularies: 'server0',
    user_login_logs: 'server3',
    short_link: 'server0',
    invitation_contacts: 'server0',
    invalid_request_log: 'server3',
    genderize_genders: 'server6',
    genderize_name_list: 'server6',
    raw_hijup_products: 'server5',
    raw_hijup_products_detail: 'server5',
    raw_hijup_categories: 'server5',
    store_categories: 'server4',
    store_products: 'server4',
    store_product_detail: 'server4',
    store_product_variants: 'server4',
    store_product_prices: 'server4',
    store_product_brands: 'server4',
    store_expedition: 'server4',
    store_province: 'server4',
    store_cities: 'server4',
    ongkos_kirim_id_cities: 'server5',
    ongkos_kirim_id_kecamatan: 'server5',
    ongkos_kirim_id_countries: 'server5',
    ongkos_kirim_id_price: 'server5'
}
